### ISSUE TITLE
Windows instructions

### ISSUE THREAD

**Issue by g-duff** [g-duff/spectrum_peak_plotter#4]
Insert complete instructions for installing and running the python program on windows 10.

**Comment by g-duff** [comment]
Drafted. Proofread when you have time.

**Comment by jm1261** [comment]
The only comment I have here is that windows doesn't seem to have an "open in terminal" option on Windows 10. Not that I can see anyway. It likes to suggest power terminal more than anything

**Comment by g-duff** [comment]
Nice. I've included a sub-point about a "power shell" window for clarity
